name: Hello world

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    container:
      image: archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup user
        run: |
          useradd -s /bin/bash runner
          mkdir /home/runner
          chown runner:runner /home/runner
          echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      - name: blah blah
        run: |
          set -x
          cat /etc/passwd
          echo "I am $(whoami)"
          su - runner
          echo "I am $(whoami)"
      # - name: create package
      #   user: runner
      #   workdir: /home/runner
      #   run: |
      #     ls -al


