name: Hello world

on: [push]

jobs:
 hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    container:
      image: archlinux:latest
    steps:
    - name: asdf
      run: ls -la && uname -a
