name: Hello world

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: arch linux create user
        uses: archlinux-latest
        run: useradd -m archie
      - name: arch linux create user
        uses: archlinux-latest
        run: cat /etc/passwd


