name: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: archlinux-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world";
          uname -a;
          cat /etc/*release;
